### ISSUE TITLE
Change `scheduler` in documentation to `cycler schedule` 

### ISSUE THREAD

**Issue by chintanp** [shriyachallam/maccorcyclingdata#4]
I see scheduler mentioned here: https://maccorcyclingdata.readthedocs.io/en/latest/features.html#the-validate-test-data-function Unless this is not referring to cycler schedule, this should be changed as such, as the word 'scheduler' has a specific meaning in S/W dev.

**Comment by shriyachallam** [comment]
Fixed - commit 78f69ad
