### ISSUE TITLE
Describe validation tests with appropriate maths

### ISSUE THREAD

**Issue by chintanp** [shriyachallam/maccorcyclingdata#5]
For example: 
* if during all the rest steps, the battery is actually resting

For this validation, in documentation, it might be helpful if you mention what exactly are you checking in terms of the code, i.e. 
> i = 0

as meaning of resting may not be apparent to someone who is new to the field. There are further other possible ways to test for resting, (voltage falling or constant, temp falling or constant, etc.) which method of validation you use here must be well documented as someone might want to add or edit it for their usecase. Let me know if I can explain this better.

**Comment by shriyachallam** [comment]
This is already specified in the docstring underneath the function.
It says that it checks for resting by making sure the current is at 0.
