### ISSUE TITLE
For every dataframe argument or return value, specify column requirement

### ISSUE THREAD

**Issue by chintanp** [shriyachallam/maccorcyclingdata#6]
We ask for dataframe arguments to functions and functions in python often return dataframes. But it may not be obvious to the user what the dataframe should look like. 

For example, does it need to have certain number of columns, or certain names of columns, or columns of certain datatypes etc. This applies to both arguments as well as return values. I am not sure of the best practice here. Maybe refer to a few documentation examples to see how people are addressing this.

**Comment by chintanp** [comment]
- Maybe scratch this if done, I see later that `validation_df` was defined. But still review the code once to see that all return dataframes are defined as well.

**Comment by shriyachallam** [comment]
Fixed commit 6a25afa
Specified that the df input or the schedule_df input must be from the output of the previous functions (import_maccor_data and import_schedules)
