### ISSUE TITLE
be specific with error and warning messages

### ISSUE THREAD

**Issue by chintanp** [shriyachallam/maccorcyclingdata#7]
For example: 

https://github.com/shriyachallam/maccorcyclingdata/blob/076a18f582fac2ad8a236b14b8afff8a7aba8287/maccorcyclingdata/validate.py#L112

In the above case, the error message reads: "error - the cycle did not advance properly". Another way to write this could be " Error - the cycle did not increase by 1 as expected" etc. 

This is a soft suggestion as language is highly subjective, and the definition of "specific" is also dynamic.

**Comment by shriyachallam** [comment]
Fixed - commit 1e1a734
